sudo: false

language: go

go:
    - 1.4

install:
    # Get our required packages
    - go get github.com/golang/lint/golint

script:
    - errors=$(gofmt -l ./src/); echo $errors; (exit $([ "$errors" == "" ]))
    - errors=$(golint ./src/...); echo $errors; (exit $([ "$errors" == "" ]))
    - go test -v ./...

matrix:
    fast_finish: true
